Traceback (most recent call last):
  File "/Users/ipasha/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/ipasha/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/ipasha/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/ipasha/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/ipasha/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/ipasha/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/Users/ipasha/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/ipasha/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
m82.add_configuration(config_name='primary',
                      obstype='spectroscopy',
                      slit_length=128*u.arcsec,
                      slit_width=1.5*u.arcsec,
                      PA=60*u.deg)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
[0;32m<ipython-input-9-8a1bae3e9f69>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m m82.add_configuration(config_name='primary',
[0m[1;32m      2[0m                       [0mobstype[0m[0;34m=[0m[0;34m'spectroscopy'[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m                       [0mslit_length[0m[0;34m=[0m[0;36m128[0m[0;34m*[0m[0mu[0m[0;34m.[0m[0marcsec[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m                       [0mslit_width[0m[0;34m=[0m[0;36m1.5[0m[0;34m*[0m[0mu[0m[0;34m.[0m[0marcsec[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m                       PA=60*u.deg)

[0;32m~/git/observing-suite/observing_suite/target.py[0m in [0;36madd_configuration[0;34m(self, config_name, obstype, coordinates, coord_units, **kwargs)[0m
[1;32m     86[0m     '''
[1;32m     87[0m     [0;32mif[0m [0mconfig_name[0m [0;32min[0m [0mself[0m[0;34m.[0m[0mconfigs[0m[0;34m.[0m[0mkeys[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 88[0;31m         [0mcont[0m [0;34m=[0m [0minput[0m[0;34m([0m[0;34mf'Config Name {config_name} already a configuration. Overwrite? [Enter yes, N for no]: '[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     89[0m         [0;32mif[0m  [0mcont[0m[0;34m.[0m[0mupper[0m[0;34m([0m[0;34m)[0m [0;34m==[0m [0;34m'N'[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     90[0m             [0;32mreturn[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/envs/a330/lib/python3.8/site-packages/ipykernel/kernelbase.py[0m in [0;36mraw_input[0;34m(self, prompt)[0m
[1;32m    855[0m         """
[1;32m    856[0m         [0;32mif[0m [0;32mnot[0m [0mself[0m[0;34m.[0m[0m_allow_stdin[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 857[0;31m             raise StdinNotImplementedError(
[0m[1;32m    858[0m                 [0;34m"raw_input was called, but this frontend does not support input requests."[0m[0;34m[0m[0;34m[0m[0m
[1;32m    859[0m             )

[0;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

